### ISSUE TITLE
Fix link provided in About section

### ISSUE THREAD

**Issue by githinho** [AMPnet/uni-widget-iframe#1]
Provided link: https://uni-widget-iframe.vercel.app/ is not working

Console error: ```The stylesheet https://uni-widget-iframe.vercel.app/~@fontsource/ibm-plex-mono/400.css was not loaded because its MIME type, "text/html", is not "text/css".```

**Comment by mightymatth** [comment]
![image](https://user-images.githubusercontent.com/13491551/154115914-46c034d0-023e-4291-a1c7-d0463f718e73.png)
the commit message speaks for itself.
